"""
build_notebooks.py
===================
Programmatically constructs the 9 project notebooks (markdown + code cells)
and executes them for real using nbclient, so every notebook in
notebooks/ contains genuine, reproducible outputs (tables, printed metrics,
inline charts) rather than static placeholders.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf
from nbclient import NotebookClient

NB_DIR = Path(__file__).resolve().parents[1] / "notebooks"
NB_DIR.mkdir(exist_ok=True)

PREAMBLE = """\
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
%matplotlib inline
"""


def md(text: str):
    return nbf.v4.new_markdown_cell(text)


def code(text: str):
    return nbf.v4.new_code_cell(text)


def make_notebook(cells: list) -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    nb["metadata"] = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12"},
    }
    return nb


def execute_and_save(nb, filename: str):
    client = NotebookClient(nb, timeout=600, kernel_name="python3")
    client.execute()
    path = NB_DIR / filename
    with open(path, "w") as f:
        nbf.write(nb, f)
    print(f"Executed & saved: {path}")


# =============================================================================
# 01 - Data Loading
# =============================================================================
nb01 = make_notebook([
    md("# 01 - Data Loading\n"
       "Loading the Global Weather Repository dataset and profiling its structure.\n\n"
       "**Note:** This sandbox has no network access to kaggle.com, so "
       "`data/raw/GlobalWeatherRepository.csv` is a schema-matched synthetic "
       "stand-in generated by `scripts/generate_sample_dataset.py`. Drop the real "
       "Kaggle CSV in the same path to use actual data — every cell below is "
       "unchanged either way."),
    code(PREAMBLE),
    code("from src.data_loader import load_raw_data, profile_dataset, print_profile\n\n"
         "df = load_raw_data()\n"
         "df.head()"),
    md("## Shape, columns, and dtypes"),
    code("print('Shape:', df.shape)\nprint('\\nColumns:', list(df.columns))"),
    code("df.dtypes"),
    md("## Summary statistics"),
    code("df.describe(include='number').T"),
    md("## Memory usage, duplicates, missing values"),
    code("print_profile(df)"),
    md("## Save profile for later phases"),
    code("profile = profile_dataset(df)\nprint('Duplicate rows:', profile['duplicate_rows'])\n"
         "print('Total missing cells:', sum(profile['missing_values'].values()))"),
])

# =============================================================================
# 02 - Data Cleaning
# =============================================================================
nb02 = make_notebook([
    md("# 02 - Data Cleaning\n"
       "Duplicate removal, missing-value imputation, outlier treatment (IQR & "
       "Z-score), datetime parsing, and validation."),
    code(PREAMBLE),
    code("import pandas as pd\n"
         "from src import config\n"
         "from src.data_loader import load_raw_data\n"
         "from src.preprocessing import (remove_duplicates, handle_missing_values, handle_outliers,\n"
         "                                parse_datetime, detect_outliers_iqr, detect_outliers_zscore,\n"
         "                                validate_dataset, clean_pipeline)\n\n"
         "raw = load_raw_data()\n"
         "print('Raw shape:', raw.shape)"),
    md("## Step 1: Remove duplicates"),
    code("df = remove_duplicates(raw)"),
    md("## Step 2: Parse datetime"),
    code("df = parse_datetime(df)\ndf[config.DATETIME_COL].head()"),
    md("## Step 3: Missing value imputation (median strategy)"),
    code("print('Missing before:', df.isna().sum().sum())\n"
         "df = handle_missing_values(df, strategy='median')\n"
         "print('Missing after:', df.isna().sum().sum())"),
    md("## Step 4: Outlier detection (IQR method) — demonstration on temperature"),
    code("mask_iqr = detect_outliers_iqr(df['temperature_celsius'])\n"
         "mask_z = detect_outliers_zscore(df['temperature_celsius'])\n"
         "print(f'IQR outliers: {mask_iqr.sum()}')\n"
         "print(f'Z-score outliers: {mask_z.sum()}')"),
    md("## Step 5: Outlier treatment (clip to IQR bounds) across numeric columns"),
    code("df = handle_outliers(df, method='iqr', action='clip')"),
    md("## Step 6: Validation report"),
    code("report = validate_dataset(df)\nreport"),
    md("## Save cleaned dataset"),
    code("df.to_csv(config.CLEAN_DATA_FILE, index=False)\n"
         "print('Saved to', config.CLEAN_DATA_FILE)\n"
         "print('Final shape:', df.shape)"),
])

# =============================================================================
# 03 - EDA
# =============================================================================
nb03 = make_notebook([
    md("# 03 - Exploratory Data Analysis\n"
       "40+ professional visualizations covering distributions, relationships, "
       "trends, and rankings. See also `scripts/run_eda.py`, which generates the "
       "full chart set to `outputs/figures/`."),
    code(PREAMBLE),
    code("import pandas as pd\n"
         "from src import config, visualization as viz\n\n"
         "df = pd.read_csv(config.CLEAN_DATA_FILE, parse_dates=[config.DATETIME_COL])\n"
         "df.shape"),
    md("## Temperature distribution"),
    code("fig = viz.plot_distribution(df, 'temperature_celsius'); fig"),
    md("## Humidity distribution"),
    code("fig = viz.plot_distribution(df, 'humidity'); fig"),
    md("## Temperature by country (boxplot)"),
    code("fig = viz.plot_boxplot_by_group(df, 'temperature_celsius', 'country'); fig"),
    md("## Correlation heatmap"),
    code("cols = ['temperature_celsius','humidity','pressure_mb','wind_kph','cloud','visibility_km','uv_index','precip_mm']\n"
         "fig = viz.plot_correlation_heatmap(df, cols); fig"),
    md("## Daily temperature trend (global average)"),
    code("fig = viz.plot_time_trend(df, config.DATETIME_COL, 'temperature_celsius', freq='D'); fig"),
    md("## Hottest & coldest countries"),
    code("fig = viz.plot_country_ranking(df, 'temperature_celsius', ascending=False); fig"),
    code("fig = viz.plot_country_ranking(df, 'temperature_celsius', ascending=True); fig"),
    md("## Humidity vs temperature scatter"),
    code("fig = viz.plot_scatter(df, 'humidity', 'temperature_celsius'); fig"),
    md("## Full chart set\n"
       "The complete 40+ chart battery (violin plots, pairplots, seasonal "
       "comparisons, condition/moon-phase frequency, day-of-week & monthly "
       "patterns, etc.) is generated by running:\n"
       "```bash\n"
       "python scripts/run_eda.py\n"
       "```\n"
       "All resulting PNGs are saved to `outputs/figures/`."),
])

# =============================================================================
# 04 - Feature Engineering
# =============================================================================
nb04 = make_notebook([
    md("# 04 - Feature Engineering\n"
       "Calendar features, comfort indices (heat index, wind chill, humidity "
       "index), lag/rolling statistics, and interaction features."),
    code(PREAMBLE),
    code("import pandas as pd\n"
         "from src import config\n"
         "from src.feature_engineering import (add_calendar_features, add_comfort_indices,\n"
         "                                      add_lag_rolling_features, add_interaction_features,\n"
         "                                      build_features, select_features)\n\n"
         "df = pd.read_csv(config.CLEAN_DATA_FILE, parse_dates=[config.DATETIME_COL])\n"
         "df.shape"),
    md("## Calendar features"),
    code("df = add_calendar_features(df)\n"
         "df[['year','month','day','week_of_year','quarter','is_weekend','season']].head()"),
    md("## Comfort indices"),
    code("df = add_comfort_indices(df)\n"
         "df[['temperature_celsius','feels_like_celsius','temp_feels_diff','heat_index','wind_chill','humidity_index']].head()"),
    md("## Lag & rolling features (per-location time series)"),
    code("df = add_lag_rolling_features(df)\n"
         "[c for c in df.columns if 'lag_' in c or 'rollmean' in c or 'rollstd' in c]"),
    md("## Interaction & polynomial features"),
    code("df = add_interaction_features(df)\n"
         "df[['humidity_temp_interaction','wind_pressure_interaction','temperature_celsius_sq']].head()"),
    md("## Feature selection (top correlated with target)"),
    code("top_features = select_features(df, top_k=15)\ntop_features"),
    md("## Save feature-engineered dataset"),
    code("df.to_csv(config.FEATURED_DATA_FILE, index=False)\n"
         "print('Saved:', config.FEATURED_DATA_FILE, '| shape:', df.shape)"),
])

# =============================================================================
# 05 - Model Training
# =============================================================================
nb05 = make_notebook([
    md("# 05 - Model Training\n"
       "Trains Linear Regression, Decision Tree, Random Forest, Gradient "
       "Boosting, SVR, XGBoost, and LightGBM to predict `temperature_celsius`.\n\n"
       "**Leakage note:** engineered features that are deterministic functions "
       "of *today's* temperature (heat index, wind chill, feels-like, etc.) are "
       "excluded from the feature matrix — see `src/train.py::get_feature_matrix` "
       "for details. Only past-looking lag/rolling temperature features are kept."),
    code(PREAMBLE),
    code("import pandas as pd\n"
         "from src import config\n"
         "from src.train import get_feature_matrix, train_test_split_data, train_all_models, build_ensemble\n\n"
         "df = pd.read_csv(config.FEATURED_DATA_FILE, parse_dates=[config.DATETIME_COL])\n"
         "X, y, feature_cols = get_feature_matrix(df)\n"
         "print('Feature matrix:', X.shape)\nprint('Features:', feature_cols)"),
    code("X_train, X_test, y_train, y_test = train_test_split_data(X, y)\n"
         "print('Train:', X_train.shape, ' Test:', X_test.shape)"),
    md("## Train all models"),
    code("fitted_models = train_all_models(X_train, y_train)\nlist(fitted_models.keys())"),
    md("## Build a simple weighted-average ensemble"),
    code("import joblib\n"
         "ensemble_pred = build_ensemble(fitted_models, X_test)\n"
         "joblib.dump(fitted_models, config.MODELS_DIR / 'all_models_bundle.pkl')\n"
         "ensemble_pred[:10]"),
])

# =============================================================================
# 06 - TimeSeries Forecasting
# =============================================================================
nb06 = make_notebook([
    md("# 06 - Time-Series Forecasting\n"
       "ARIMA, SARIMA, and Prophet (with a statsmodels-based fallback when "
       "Prophet isn't installed) forecasts of daily average global temperature."),
    code(PREAMBLE),
    code("import pandas as pd\n"
         "from src import config\n"
         "from src.forecasting import (build_daily_series, forecast_arima, forecast_sarima,\n"
         "                              forecast_prophet_or_fallback, evaluate_forecast)\n\n"
         "df = pd.read_csv(config.CLEAN_DATA_FILE, parse_dates=[config.DATETIME_COL])\n"
         "daily = build_daily_series(df)\n"
         "daily.plot(figsize=(11,4), title='Global Daily Avg Temperature'); plt.ylabel('°C'); plt.show()"),
    md("## ARIMA forecast"),
    code("arima_mean, arima_ci, arima_model = forecast_arima(daily)\narima_mean"),
    md("## SARIMA forecast (weekly seasonality)"),
    code("sarima_mean, sarima_ci, sarima_model = forecast_sarima(daily)\nsarima_mean"),
    md("## Prophet / fallback forecast"),
    code("prophet_fc = forecast_prophet_or_fallback(daily)\nprophet_fc"),
    md("## Visualize all three forecasts together"),
    code("plt.figure(figsize=(12,5))\n"
         "plt.plot(daily.index, daily.values, label='Historical', color='black')\n"
         "plt.plot(arima_mean.index, arima_mean.values, label='ARIMA', linestyle='--')\n"
         "plt.plot(sarima_mean.index, sarima_mean.values, label='SARIMA', linestyle='--')\n"
         "plt.plot(prophet_fc.index, prophet_fc.values, label='Prophet/Fallback', linestyle='--')\n"
         "plt.legend(); plt.title('14-Day Temperature Forecast Comparison'); plt.ylabel('°C'); plt.show()"),
])

# =============================================================================
# 07 - Advanced Analytics
# =============================================================================
nb07 = make_notebook([
    md("# 07 - Advanced Analytics\n"
       "Anomaly detection (Isolation Forest, LOF), clustering (DBSCAN, KMeans), "
       "PCA, permutation/SHAP explainability, climate-trend & heatwave analysis."),
    code(PREAMBLE),
    code("import pandas as pd\n"
         "from src import config\n"
         "from src.advanced_analytics import (detect_anomalies_isolation_forest, detect_anomalies_lof,\n"
         "                                     cluster_dbscan, cluster_kmeans, run_pca,\n"
         "                                     climate_trend_analysis, detect_heatwaves, country_ranking)\n\n"
         "df = pd.read_csv(config.CLEAN_DATA_FILE, parse_dates=[config.DATETIME_COL])\n"
         "cols = ['temperature_celsius','humidity','pressure_mb','wind_kph']"),
    md("## Isolation Forest anomaly detection"),
    code("if_labels, _ = detect_anomalies_isolation_forest(df, cols)\n"
         "print('Anomalies flagged:', (if_labels == -1).sum())"),
    md("## Local Outlier Factor"),
    code("lof_labels = detect_anomalies_lof(df, cols)\nprint('LOF anomalies:', (lof_labels == -1).sum())"),
    md("## KMeans weather-regime clustering"),
    code("k_labels, kmeans_model = cluster_kmeans(df, cols, n_clusters=4)\n"
         "pd.Series(k_labels).value_counts().sort_index()"),
    md("## DBSCAN density-based clustering"),
    code("db_labels = cluster_dbscan(df, cols)\npd.Series(db_labels).value_counts().sort_index()"),
    md("## PCA dimensionality reduction"),
    code("pca_transformed, pca_model = run_pca(df, cols, n_components=2)\n"
         "print('Explained variance ratio:', pca_model.explained_variance_ratio_)"),
    md("## Climate trend analysis"),
    code("trend = climate_trend_analysis(df, config.DATETIME_COL, 'temperature_celsius')\ntrend"),
    md("## Heatwave detection"),
    code("heatwaves = detect_heatwaves(df)\nprint(f'{len(heatwaves)} heatwave events detected')\nheatwaves.head(10)"),
    md("## Country temperature ranking"),
    code("country_ranking(df, 'temperature_celsius').to_frame('avg_temp_c')"),
])

# =============================================================================
# 08 - Model Comparison
# =============================================================================
nb08 = make_notebook([
    md("# 08 - Model Comparison & Evaluation\n"
       "MAE, MSE, RMSE, MAPE, R², cross-validation, residual analysis, and "
       "feature importance / explainability for the best model."),
    code(PREAMBLE),
    code("import joblib\nimport pandas as pd\n"
         "from src import config\n"
         "from src.train import get_feature_matrix, train_test_split_data\n"
         "from src.evaluate import evaluate_models, cross_validate_model, get_best_model\n"
         "from src.advanced_analytics import compute_permutation_importance\n\n"
         "df = pd.read_csv(config.FEATURED_DATA_FILE, parse_dates=[config.DATETIME_COL])\n"
         "X, y, feature_cols = get_feature_matrix(df)\n"
         "X_train, X_test, y_train, y_test = train_test_split_data(X, y)\n\n"
         "model_names = ['LinearRegression','DecisionTree','RandomForest','GradientBoosting','SVR','XGBoost','LightGBM']\n"
         "fitted = {n: joblib.load(config.MODELS_DIR / f'{n}.pkl') for n in model_names if (config.MODELS_DIR / f'{n}.pkl').exists()}\n"
         "list(fitted.keys())"),
    md("## Comparison table (sorted by RMSE)"),
    code("results = evaluate_models(fitted, X_test, y_test)\nresults"),
    md("## Best model + 5-fold cross-validation"),
    code("best_name, best_model = get_best_model(results, fitted)\n"
         "cv = cross_validate_model(best_model, X, y)\n"
         "print(f'Best model: {best_name}')\n"
         "print(f\"CV RMSE: {cv['mean']:.3f} +/- {cv['std']:.3f}\")"),
    md("## Feature importance (best model)"),
    code("if hasattr(best_model, 'feature_importances_'):\n"
         "    imp = pd.Series(best_model.feature_importances_, index=feature_cols).sort_values(ascending=False)\n"
         "    display(imp.head(15))\n"
         "else:\n"
         "    print('Model has no native feature_importances_; see permutation importance below.')"),
    md("## Permutation importance"),
    code("perm_imp = compute_permutation_importance(best_model, X_test, y_test, n_repeats=5)\nperm_imp.head(15)"),
])

# =============================================================================
# 09 - Dashboard
# =============================================================================
nb09 = make_notebook([
    md("# 09 - Dashboard (Preview)\n"
       "The full interactive dashboard lives in `dashboard/app.py` and is built "
       "with Streamlit. This notebook renders a static preview of the same "
       "views using Plotly, so the key visuals are inspectable without running "
       "the Streamlit server."),
    code(PREAMBLE),
    code("import pandas as pd\nimport plotly.express as px\n"
         "from src import config\n\n"
         "df = pd.read_csv(config.FEATURED_DATA_FILE, parse_dates=[config.DATETIME_COL])\n"
         "latest = df.sort_values(config.DATETIME_COL).groupby('location_name').tail(1)\n"
         "fig = px.scatter_geo(latest, lat='latitude', lon='longitude', color='temperature_celsius',\n"
         "                     hover_name='location_name', color_continuous_scale='RdYlBu_r',\n"
         "                     projection='natural earth', title='Global Temperature Snapshot')\n"
         "fig.show()"),
    code("fig2 = px.line(df.set_index(config.DATETIME_COL)['temperature_celsius'].resample('D').mean(),\n"
         "               title='Global Daily Average Temperature Trend')\n"
         "fig2.show()"),
    md("## Launching the full dashboard\n"
       "```bash\n"
       "streamlit run dashboard/app.py\n"
       "```\n"
       "Pages: Home, Dataset, EDA, Climate Trends, Forecast (incl. manual "
       "prediction input), Model Comparison, Maps, and About — with country/date "
       "filters, dark-mode toggle, and CSV download in the sidebar."),
])


NOTEBOOKS = [
    ("01_Data_Loading.ipynb", nb01),
    ("02_Data_Cleaning.ipynb", nb02),
    ("03_EDA.ipynb", nb03),
    ("04_Feature_Engineering.ipynb", nb04),
    ("05_Model_Training.ipynb", nb05),
    ("06_TimeSeries_Forecasting.ipynb", nb06),
    ("07_Advanced_Analytics.ipynb", nb07),
    ("08_Model_Comparison.ipynb", nb08),
    ("09_Dashboard.ipynb", nb09),
]


if __name__ == "__main__":
    for filename, nb in NOTEBOOKS:
        execute_and_save(nb, filename)
